draft({
    "draftId": "12",
    "draftDate": "05\/06\/2013",
    "draftEndDate": "05\/06\/2013",
    "draftStart": "10:00:00",
    "draftEnd": "23:00:00",
    "draftTotalAdd": "191",
    "draftTotalDelete": "280",
    "draftStatus": "FINAL",
    "draftResultsTitle": "",
    "draftPurchase": "37",
    "draftLoan": "67",
    "draftTotal": "$476,316,090 M.N",
    "draftTransfers": "100",
    "draftURL": "http:\/\/mxm.televisadeportes.esmas.com\/futbol\/draft\/liga-mx-apertura-2013\/",
    "draftTournament": {
        "name": "Liga MX Apertura 2013",
        "dateTime": "2013-07-19 19:30:00",
        "url": "",
        "calendarURL": ""
    },
    "draftTeams": [
        {
            "id": "1",
            "name": "Am\u00e9rica",
            "teamAdd": "5",
            "teamDelete": "7",
            "teamRumor": "0",
            "groupName": "",
            "groupId": "",
            "SquadURL": "",
            "logos": [
                {
                    "size": "70x70",
                    "type": "gif",
                    "URL": "http:\/\/i2.esmas.com\/sef\/img\/club\/escudom2\/70x704YRe7k.png"
                },
                {
                    "size": "129x130",
                    "type": "jpg",
                    "URL": "http:\/\/i2.esmas.com\/sef\/img\/club\/escudodraft\/america_130x130VsdBrt.jpg"
                }
            ],
            "operation": [
                {
                    "id": "2271",
                    "type": "BAJA",
                    "nationality": "Mexicana",
                    "name": "Alvarado, Ventura",
                    "acquire": "Necaxa",
                    "transfer": "Am\u00e9rica",
                    "lastTeam": "Am\u00e9rica",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/venturaalvarado\/20440",
                    "rantingTD": "1",
                    "rantingTDL": "1",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "2242",
                    "type": "ALTA",
                    "nationality": "Colombiana",
                    "name": "Andrade, Andr\u00e9s Felipe",
                    "acquire": "Am\u00e9rica",
                    "transfer": "Deportes Tolima",
                    "lastTeam": "Deportes Tolima",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/andresfelipeandrade\/29407",
                    "rantingTD": "3",
                    "rantingTDL": "3",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "2234",
                    "type": "BAJA",
                    "nationality": "Ecuatoriana",
                    "name": "Ben\u00edtez, Christian Rogelio",
                    "acquire": "El Jaish SC",
                    "transfer": "Am\u00e9rica",
                    "lastTeam": "Am\u00e9rica",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/christianrogeliobenitez\/2161",
                    "rantingTD": "4",
                    "rantingTDL": "4",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "2191",
                    "type": "ALTA",
                    "nationality": "Mexicana",
                    "name": "Pimentel, Erik Alan",
                    "acquire": "Am\u00e9rica",
                    "transfer": "Am\u00e9rica",
                    "lastTeam": "Atlante",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/erikalanpimentel\/14525",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "2133",
                    "type": "BAJA",
                    "nationality": "Mexicana",
                    "name": "Urias, Jorge Alberto",
                    "acquire": "Zacatepec",
                    "transfer": "Am\u00e9rica",
                    "lastTeam": "Am\u00e9rica",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/jorgealbertourias\/14526",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "2131",
                    "type": "BAJA",
                    "nationality": "Mexicana",
                    "name": "Garc\u00eda, Irving Jassiel",
                    "acquire": "Zacatepec",
                    "transfer": "Am\u00e9rica",
                    "lastTeam": "Am\u00e9rica",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/irvingjassielgarcia\/20835",
                    "rantingTD": "1",
                    "rantingTDL": "1",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "2114",
                    "type": "PRESTAMO",
                    "nationality": "Mexicana",
                    "name": "Z\u00fa\u00f1iga, Mart\u00edn Eduardo",
                    "acquire": "Chiapas FC",
                    "transfer": "Am\u00e9rica",
                    "lastTeam": "Am\u00e9rica",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/martineduardozuniga\/12569",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "2117",
                    "type": "COMPRA",
                    "nationality": "Mexicana",
                    "name": "Rojas, \u00d3scar Adri\u00e1n",
                    "acquire": "Puebla",
                    "transfer": "Am\u00e9rica",
                    "lastTeam": "Pachuca",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/oscar-adrian-rojas\/120",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "2109",
                    "type": "COMPRA",
                    "nationality": "Mexicana",
                    "name": "Mendoza, Luis \u00c1ngel",
                    "acquire": "Am\u00e9rica",
                    "transfer": "Chiapas FC",
                    "lastTeam": "San Luis",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/luisangelmendoza\/5985",
                    "rantingTD": "3",
                    "rantingTDL": "3",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "2108",
                    "type": "PRESTAMO",
                    "nationality": "Mexicana",
                    "name": "Ju\u00e1rez, Efra\u00edn",
                    "acquire": "Monterrey",
                    "transfer": "Am\u00e9rica",
                    "lastTeam": "Am\u00e9rica",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/efrain-juarez\/2241",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "2122",
                    "type": "COMPRA",
                    "nationality": "Colombia",
                    "name": "Rey, Luis Gabriel",
                    "acquire": "Am\u00e9rica",
                    "transfer": "Quer\u00e9taro FC",
                    "lastTeam": "Jaguares",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/luis-gabriel-rey\/274",
                    "rantingTD": "4",
                    "rantingTDL": "4",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "2093",
                    "type": "COMPRA",
                    "nationality": "Mexicana",
                    "name": "Guti\u00e9rrez, Carlos Alberto",
                    "acquire": "Am\u00e9rica",
                    "transfer": "Atlas",
                    "lastTeam": "Atlas",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/carlos-alberto-gutierrez\/4073",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "2024",
                    "type": "COMPRA",
                    "nationality": "Mexicana",
                    "name": "Corral, George Ulises",
                    "acquire": "Quer\u00e9taro FC",
                    "transfer": "Am\u00e9rica",
                    "lastTeam": "Jaguares",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/george-ulises-corral\/4431",
                    "rantingTD": "3",
                    "rantingTDL": "3",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "2087",
                    "type": "PRESTAMO",
                    "nationality": "Mexicana",
                    "name": "Navarrete, Armando",
                    "acquire": "Puebla",
                    "transfer": "Am\u00e9rica",
                    "lastTeam": "Necaxa",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/armando-navarrete\/77",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "2076",
                    "type": "COMPRA",
                    "nationality": "Mexicana",
                    "name": "Pineda, Leonin",
                    "acquire": "Veracruz",
                    "transfer": "Am\u00e9rica",
                    "lastTeam": "La Piedad",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/leoninpineda\/2260",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "2077",
                    "type": "COMPRA",
                    "nationality": "Mexicana",
                    "name": "S\u00e1nchez, Jes\u00fas Armando",
                    "acquire": "Veracruz",
                    "transfer": "Am\u00e9rica",
                    "lastTeam": "La Piedad",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/jesus-armando-sanchez\/2191",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1942",
                    "type": "BAJA",
                    "nationality": "Mexicana",
                    "name": "Reyes, Diego Antonio",
                    "acquire": "FC Porto",
                    "transfer": "Am\u00e9rica",
                    "lastTeam": "Am\u00e9rica",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/diego-antonio-reyes\/4891",
                    "rantingTD": "5",
                    "rantingTDL": "5",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                }
            ]
        },
        {
            "id": "2",
            "name": "Atlante",
            "teamAdd": "18",
            "teamDelete": "15",
            "teamRumor": "0",
            "groupName": "",
            "groupId": "",
            "SquadURL": "",
            "logos": [
                {
                    "size": "70x70",
                    "type": "gif",
                    "URL": "http:\/\/i2.esmas.com\/sef\/img\/club\/escudom2\/70x70ZJSwxK.png"
                },
                {
                    "size": "129x130",
                    "type": "jpg",
                    "URL": "http:\/\/i2.esmas.com\/deportes30\/img\/draft\/emb_atlante_draft.jpg"
                }
            ],
            "operation": [
                {
                    "id": "2278",
                    "type": "ALTA",
                    "nationality": "Argentina",
                    "name": "Nanni, Roberto Antonio",
                    "acquire": "Atlante",
                    "transfer": "Cerro Porte\u00f1o",
                    "lastTeam": "Cerro Porte\u00f1o",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/robertoantonionanni\/12842",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "2276",
                    "type": "BAJA",
                    "nationality": "Argentina",
                    "name": "Larrivey, Joaqu\u00edn Oscar",
                    "acquire": "Rayo Vallecano",
                    "transfer": "Atlante",
                    "lastTeam": "Atlante",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/joaquinoscarlarrivey\/17309",
                    "rantingTD": "3",
                    "rantingTDL": "3",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "2248",
                    "type": "CANCELADA",
                    "nationality": "Venezolana",
                    "name": "Maldonado, Giancarlo Gregorio",
                    "acquire": "Atlante",
                    "transfer": "Atlas",
                    "lastTeam": "Deportivo T\u00e1chira",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/giancarlo-gregorio-maldonado\/2156",
                    "rantingTD": "3",
                    "rantingTDL": "3",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "2274",
                    "type": "ALTA",
                    "nationality": "Argentina",
                    "name": "Miralles, Ezequiel Nicol\u00e1s",
                    "acquire": "Atlante",
                    "transfer": "Gremio",
                    "lastTeam": "Santos FC",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/ezequielnicolasmiralles\/30217",
                    "rantingTD": "3",
                    "rantingTDL": "3",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "2270",
                    "type": "CANCELADA",
                    "nationality": "Argentina",
                    "name": "Rodr\u00edguez, Patricio Juli\u00e1n",
                    "acquire": "Atlante",
                    "transfer": "Santos FC",
                    "lastTeam": "Santos FC",
                    "Detail": "Llegar\u00eda seis meses a pr\u00e9stamo",
                    "playerURL": "",
                    "rantingTD": "3",
                    "rantingTDL": "3",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "2250",
                    "type": "ALTA",
                    "nationality": "Argentina",
                    "name": "Erviti, Walter Daniel",
                    "acquire": "Atlante",
                    "transfer": "Boca Juniors",
                    "lastTeam": "Boca Juniors",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/walterdanielerviti\/340",
                    "rantingTD": "3",
                    "rantingTDL": "3",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "2240",
                    "type": "ALTA",
                    "nationality": "Argentina",
                    "name": "Romero, Mauricio Mart\u00edn",
                    "acquire": "Atlante",
                    "transfer": "Morelia",
                    "lastTeam": "Col\u00f3n de Santa Fe",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/mauricio-martin-romero\/2167",
                    "rantingTD": "3",
                    "rantingTDL": "3",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "2239",
                    "type": "BAJA",
                    "nationality": "Uruguaya",
                    "name": "Bizera, Joe Emerson",
                    "acquire": "Por definir",
                    "transfer": "Atlante",
                    "lastTeam": "Atlante",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/joeemersonbizera\/1135",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "2235",
                    "type": "ALTA",
                    "nationality": "Argentina",
                    "name": "Galmarini, Mart\u00edn Sebasti\u00e1n",
                    "acquire": "Atlante",
                    "transfer": "Tigre",
                    "lastTeam": "Tigre",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/martinsebastiangalmarini\/29359",
                    "rantingTD": "3",
                    "rantingTDL": "3",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "2191",
                    "type": "ALTA",
                    "nationality": "Mexicana",
                    "name": "Pimentel, Erik Alan",
                    "acquire": "Am\u00e9rica",
                    "transfer": "Am\u00e9rica",
                    "lastTeam": "Atlante",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/erikalanpimentel\/14525",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "2268",
                    "type": "ALTA",
                    "nationality": "Mexicana",
                    "name": "Diego, Alex",
                    "acquire": "Atlante",
                    "transfer": "Atlante",
                    "lastTeam": "Lobos BUAP",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/alexdiego\/1418",
                    "rantingTD": "1",
                    "rantingTDL": "1",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "2201",
                    "type": "ALTA",
                    "nationality": "Mexicana",
                    "name": "Pati\u00f1o, Eder",
                    "acquire": "Atlante",
                    "transfer": "Atlante",
                    "lastTeam": "M\u00e9rida",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/ederpatino\/11288",
                    "rantingTD": "1",
                    "rantingTDL": "1",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "2166",
                    "type": "ALTA",
                    "nationality": "Mexicana",
                    "name": "Hern\u00e1ndez, Jorge",
                    "acquire": "Atlante",
                    "transfer": "Atlante",
                    "lastTeam": "Tijuana",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/jorge-hernandez\/2187",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "2177",
                    "type": "ALTA",
                    "nationality": "Mexicana",
                    "name": "Garc\u00eda, Diego",
                    "acquire": "Atlante",
                    "transfer": "Atl\u00e9tico San Luis",
                    "lastTeam": "Veracruz",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/diego-garcia\/4203",
                    "rantingTD": "1",
                    "rantingTDL": "1",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1924",
                    "type": "BAJA",
                    "nationality": "Mexicana",
                    "name": "Ordaz, Diego Alejandro",
                    "acquire": "Lobos BUAP",
                    "transfer": "Chiapas FC",
                    "lastTeam": "Atlante",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/diego-alejandro-ordaz\/345",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "2158",
                    "type": "ALTA",
                    "nationality": "Mexicana",
                    "name": "Orozco, Ezequiel Francisco",
                    "acquire": "Atlante",
                    "transfer": "Necaxa",
                    "lastTeam": "Necaxa",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/ezequielfranciscoorozco\/4489",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "2153",
                    "type": "BAJA",
                    "nationality": "Mexicana",
                    "name": "Arredondo, Alejandro",
                    "acquire": "Delfines",
                    "transfer": "Atlante",
                    "lastTeam": "Atlante",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/alejandroarredondo\/472",
                    "rantingTD": "1",
                    "rantingTDL": "1",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1967",
                    "type": "PRESTAMO",
                    "nationality": "Mexicana",
                    "name": "Sep\u00falveda, \u00c1ngel Baltazar",
                    "acquire": "Atlante",
                    "transfer": "Quer\u00e9taro FC",
                    "lastTeam": "Neza",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/angelbaltazarsepulveda\/12000",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                })