draft({
    "draftId": "11",
    "draftDate": "19\/12\/2012",
    "draftEndDate": "20\/12\/2012",
    "draftStart": "12:00:00",
    "draftEnd": "20:30:00",
    "draftTotalAdd": "106",
    "draftTotalDelete": "172",
    "draftStatus": "FINAL",
    "draftResultsTitle": "",
    "draftPurchase": "27",
    "draftLoan": "41",
    "draftTotal": "$211,399,600 M.N.",
    "draftTransfers": "68",
    "draftURL": "http:\/\/mxm.televisadeportes.esmas.com\/futbol\/draft\/liga-mx-clausura-2013\/",
    "draftTournament": {
        "name": "Liga MX Clausura 2013",
        "dateTime": "2013-01-04 19:30:00",
        "url": "",
        "calendarURL": ""
    },
    "draftTeams": [
        {
            "id": "1",
            "name": "Am\u00e9rica",
            "teamAdd": "3",
            "teamDelete": "7",
            "teamRumor": "0",
            "groupName": "",
            "groupId": "",
            "SquadURL": "",
            "logos": [
                {
                    "size": "70x70",
                    "type": "gif",
                    "URL": "http:\/\/i2.esmas.com\/sef\/img\/club\/escudom2\/america_70x702pXNp0.png"
                },
                {
                    "size": "129x130",
                    "type": "jpg",
                    "URL": "http:\/\/i2.esmas.com\/sef\/img\/club\/escudodraft\/america_130x130VsdBrt.jpg"
                }
            ],
            "operation": [
                {
                    "id": "1740",
                    "type": "BAJA",
                    "nationality": "Mexicana",
                    "name": "Acosta, Daniel",
                    "acquire": "M\u00e9rida",
                    "transfer": "Am\u00e9rica",
                    "lastTeam": "Am\u00e9rica",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/danielacosta\/20439",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1743",
                    "type": "PRESTAMO",
                    "nationality": "Mexicana",
                    "name": "M\u00e1rquez, Daniel Omar",
                    "acquire": "Tijuana",
                    "transfer": "Am\u00e9rica",
                    "lastTeam": "Necaxa",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/daniel-omar-marquez\/2223",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1889",
                    "type": "ALTA",
                    "nationality": "Mexicana",
                    "name": "Rodr\u00edguez, Francisco Javier",
                    "acquire": "Am\u00e9rica",
                    "transfer": "VfB Stuttgart",
                    "lastTeam": "VfB Stuttgart",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/francisco-javier-rodriguez\/244",
                    "rantingTD": "4",
                    "rantingTDL": "4",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1797",
                    "type": "COMPRA",
                    "nationality": "Paraguaya",
                    "name": "Mart\u00ednez, Osvaldo David",
                    "acquire": "Am\u00e9rica",
                    "transfer": "Atlante",
                    "lastTeam": "Atlante",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/osvaldo-david-martinez\/4467",
                    "rantingTD": "4",
                    "rantingTDL": "4",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1833",
                    "type": "PRESTAMO",
                    "nationality": "Mexicana",
                    "name": "Pimentel, Erik Alan",
                    "acquire": "Atlante",
                    "transfer": "Am\u00e9rica",
                    "lastTeam": "Am\u00e9rica",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/erikalanpimentel\/14525",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1832",
                    "type": "PRESTAMO",
                    "nationality": "Mexicana",
                    "name": "Acu\u00f1a, Isaac",
                    "acquire": "Atlante",
                    "transfer": "Am\u00e9rica",
                    "lastTeam": "M\u00e9rida",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/isaacacuna\/11227",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1826",
                    "type": "PRESTAMO",
                    "nationality": "Mexicana",
                    "name": "C\u00e1rdenas, Jos\u00e9 Mar\u00eda",
                    "acquire": "Morelia",
                    "transfer": "Am\u00e9rica",
                    "lastTeam": "Am\u00e9rica",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/jose-maria-cardenas\/1380",
                    "rantingTD": "3",
                    "rantingTDL": "3",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1734",
                    "type": "BAJA",
                    "nationality": "Brasile\u00f1a",
                    "name": "Adolfo, Rosinei",
                    "acquire": "A. Mineiro",
                    "transfer": "Am\u00e9rica",
                    "lastTeam": "Am\u00e9rica",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/rosinei-adolfo\/4403",
                    "rantingTD": "3",
                    "rantingTDL": "3",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1803",
                    "type": "ALTA",
                    "nationality": "Ecuatoriana",
                    "name": "Mina, Arrinton Narciso",
                    "acquire": "Am\u00e9rica",
                    "transfer": "Barcelona de Guayaquil",
                    "lastTeam": "Barcelona de Guayaquil",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/arrintonnarcisomina\/13281",
                    "rantingTD": "4",
                    "rantingTDL": "4",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1741",
                    "type": "BAJA",
                    "nationality": "Mexicana",
                    "name": "Garc\u00eda, Pedro Antonio",
                    "acquire": "M\u00e9rida",
                    "transfer": "Am\u00e9rica",
                    "lastTeam": "Am\u00e9rica",
                    "Detail": "Transferible",
                    "playerURL": "\/futbol\/jugadores\/pedroantoniogarcia\/16428",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1739",
                    "type": "BAJA",
                    "nationality": "Mexicana",
                    "name": "Reyes, Jorge",
                    "acquire": "Veracruz",
                    "transfer": "Am\u00e9rica",
                    "lastTeam": "Am\u00e9rica",
                    "Detail": "Transferible",
                    "playerURL": "\/futbol\/jugadores\/jorgereyes\/14665",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1737",
                    "type": "BAJA",
                    "nationality": "Argentina",
                    "name": "Montenegro, Daniel Gast\u00f3n",
                    "acquire": "Independiente",
                    "transfer": "Am\u00e9rica",
                    "lastTeam": "Am\u00e9rica",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/daniel-gaston-montenegro\/4561",
                    "rantingTD": "3",
                    "rantingTDL": "3",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                }
            ]
        },
        {
            "id": "2",
            "name": "Atlante",
            "teamAdd": "9",
            "teamDelete": "9",
            "teamRumor": "0",
            "groupName": "",
            "groupId": "",
            "SquadURL": "",
            "logos": [
                {
                    "size": "70x70",
                    "type": "gif",
                    "URL": "http:\/\/i2.esmas.com\/deportes30\/img\/mxmlogos\/atlante.gif"
                },
                {
                    "size": "129x130",
                    "type": "jpg",
                    "URL": "http:\/\/i2.esmas.com\/deportes30\/img\/draft\/emb_atlante_draft.jpg"
                }
            ],
            "operation": [
                {
                    "id": "1904",
                    "type": "ALTA",
                    "nationality": "Uruguaya",
                    "name": "Bizera, Joe Emerson",
                    "acquire": "Atlante",
                    "transfer": "Libertad",
                    "lastTeam": "Libertad",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/joeemersonbizera\/1135",
                    "rantingTD": "3",
                    "rantingTDL": "3",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1903",
                    "type": "BAJA",
                    "nationality": "Espa\u00f1ola",
                    "name": "Lopes, Valmiro",
                    "acquire": "Levante",
                    "transfer": "Atlante",
                    "lastTeam": "Atlante",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/valmirolopes\/15556",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1891",
                    "type": "BAJA",
                    "nationality": "Mexicana",
                    "name": "Torres, Ignacio",
                    "acquire": "M\u00e9rida",
                    "transfer": "Atlante",
                    "lastTeam": "Atlante",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/ignacio-torres\/203",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1878",
                    "type": "BAJA",
                    "nationality": "Mexicana",
                    "name": "Marrufo, Omar",
                    "acquire": "Veracruz",
                    "transfer": "Atlante",
                    "lastTeam": "Atlante",
                    "Detail": "",
                    "playerURL": "",
                    "rantingTD": "1",
                    "rantingTDL": "1",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1814",
                    "type": "PRESTAMO",
                    "nationality": "Mexicana",
                    "name": "Garc\u00eda, Alberto Jorge",
                    "acquire": "Atlante",
                    "transfer": "Quer\u00e9taro",
                    "lastTeam": "Quer\u00e9taro",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/albertojorgegarcia\/20049",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1724",
                    "type": "PRESTAMO",
                    "nationality": "Mexicana",
                    "name": "Castro, Jos\u00e9 Antonio",
                    "acquire": "Atlante",
                    "transfer": "San Luis",
                    "lastTeam": "San Luis",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/jose-antonio-castro\/188",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1797",
                    "type": "COMPRA",
                    "nationality": "Paraguaya",
                    "name": "Mart\u00ednez, Osvaldo David",
                    "acquire": "Am\u00e9rica",
                    "transfer": "Atlante",
                    "lastTeam": "Atlante",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/osvaldo-david-martinez\/4467",
                    "rantingTD": "4",
                    "rantingTDL": "4",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1783",
                    "type": "PRESTAMO",
                    "nationality": "Mexicana",
                    "name": "Ordaz, Diego Alejandro",
                    "acquire": "Atlante",
                    "transfer": "San Luis",
                    "lastTeam": "San Luis",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/diego-alejandro-ordaz\/345",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1833",
                    "type": "PRESTAMO",
                    "nationality": "Mexicana",
                    "name": "Pimentel, Erik Alan",
                    "acquire": "Atlante",
                    "transfer": "Am\u00e9rica",
                    "lastTeam": "Am\u00e9rica",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/erikalanpimentel\/14525",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1804",
                    "type": "PRESTAMO",
                    "nationality": "Mexicana",
                    "name": "Jim\u00e9nez, Ricardo Ad\u00e1n",
                    "acquire": "San Luis",
                    "transfer": "Atlante",
                    "lastTeam": "Atlante",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/ricardo-adan-jimenez\/1439",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1832",
                    "type": "PRESTAMO",
                    "nationality": "Mexicana",
                    "name": "Acu\u00f1a, Isaac",
                    "acquire": "Atlante",
                    "transfer": "Am\u00e9rica",
                    "lastTeam": "M\u00e9rida",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/isaacacuna\/11227",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1802",
                    "type": "PRESTAMO",
                    "nationality": "Mexicana",
                    "name": "P\u00e9rez, Antonio",
                    "acquire": "Quer\u00e9taro",
                    "transfer": "Atlante",
                    "lastTeam": "Atlante",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/antonioperez\/406",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1798",
                    "type": "ALTA",
                    "nationality": "Argentina",
                    "name": "Larrivey, Joaqu\u00edn Oscar",
                    "acquire": "Atlante",
                    "transfer": "Cagliari",
                    "lastTeam": "Cagliari",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/joaquinoscarlarrivey\/17309",
                    "rantingTD": "3",
                    "rantingTDL": "3",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1735",
                    "type": "ALTA",
                    "nationality": "Ecuatoriana",
                    "name": "Quiroz, Mario David",
                    "acquire": "Atlante",
                    "transfer": "Liga de Quito",
                    "lastTeam": "Liga de Quito",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/mariodavidquiroz\/12510",
                    "rantingTD": "3",
                    "rantingTDL": "3",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1857",
                    "type": "BAJA",
                    "nationality": "Ecuatoriana",
                    "name": "Guagua, Jorge Daniel",
                    "acquire": "Por definir",
                    "transfer": "Atlante",
                    "lastTeam": "Atlante",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/jorgedanielguagua\/976",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1858",
                    "type": "BAJA",
                    "nationality": "Espa\u00f1ola",
                    "name": "Lopes, Valmiro",
                    "acquire": "Por definir",
                    "transfer": "Atlante",
                    "lastTeam": "Atlante",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/valmirolopes\/15556",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1782",
                    "type": "ALTA",
                    "nationality": "Mexicana",
                    "name": "Jim\u00e9nez, Diego Octavio",
                    "acquire": "Atlante",
                    "transfer": "Morelia",
                    "lastTeam": "Tecos",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/diego-octavio-jimenez\/1378",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                }
            ]
        },
        {
            "id": "3",
            "name": "Atlas",
            "teamAdd": "7",
            "teamDelete": "9",
            "teamRumor": "0",
            "groupName": "",
            "groupId": "",
            "SquadURL": "",
            "logos": [
                {
                    "size": "70x70",
                    "type": "gif",
                    "URL": "http:\/\/i2.esmas.com\/deportes30\/img\/mxmlogos\/atlas.gif"
                },
                {
                    "size": "129x130",
                    "type": "jpg",
                    "URL": "http:\/\/i2.esmas.com\/deportes30\/img\/draft\/emb_atlas_draft.jpg"
                }
            ],
            "operation": [
                {
                    "id": "1885",
                    "type": "ALTA",
                    "nationality": "Boliviana",
                    "name": "Ch\u00e1vez, Jos\u00e9 Luis",
                    "acquire": "Atlas",
                    "transfer": "Blooming",
                    "lastTeam": "Blooming",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/joseluischavez\/13880",
                    "rantingTD": "3",
                    "rantingTDL": "3",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1884",
                    "type": "ALTA",
                    "nationality": "Chilena",
                    "name": "Millar, Rodrigo Javier",
                    "acquire": "Atlas",
                    "transfer": "Colo Colo",
                    "lastTeam": "Colo Colo",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/rodrigo-javier-millar\/1041",
                    "rantingTD": "3",
                    "rantingTDL": "3",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1710",
                    "type": "BAJA",
                    "nationality": "Argentina",
                    "name": "Zamogilny, Jorge Dami\u00e1n",
                    "acquire": "Irapuato",
                    "transfer": "Atlas",
                    "lastTeam": "Atlas",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/jorge-damian-zamogilny\/2149",
                    "rantingTD": "1",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1861",
                    "type": "BAJA",
                    "nationality": "Mexicana",
                    "name": "D\u00edaz, Christian Antonio",
                    "acquire": "U de G",
                    "transfer": "Atlas",
                    "lastTeam": "Atlas",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/christian-antonio-diaz\/4613",
                    "rantingTD": "1",
                    "rantingTDL": "1",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1860",
                    "type": "BAJA",
                    "nationality": "Mexicana",
                    "name": "S\u00e1nchez, Christian Emmanuel",
                    "acquire": "Tecos",
                    "transfer": "Atlas",
                    "lastTeam": "Atlas",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/christian-emmanuel-sanchez\/2074",
                    "rantingTD": "1",
                    "rantingTDL": "1",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1864",
                    "type": "BAJA",
                    "nationality": "Mexicana",
                    "name": "T\u00e9lles, Luis Fernando",
                    "acquire": "U de G",
                    "transfer": "Atlas",
                    "lastTeam": "Atlas",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/luisfernandotelles\/4893",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1733",
                    "type": "COMPRA",
                    "nationality": "Mexicana",
                    "name": "Rodr\u00edguez, Hugo Isaac",
                    "acquire": "Tigres",
                    "transfer": "Atlas",
                    "lastTeam": "Atlas",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/hugo-isaac-rodriguez\/11229",
                    "rantingTD": "3",
                    "rantingTDL": "3",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1778",
                    "type": "PRESTAMO",
                    "nationality": "Chilena",
                    "name": "Mancilla, H\u00e9ctor Ra\u00fal",
                    "acquire": "Morelia",
                    "transfer": "Atlas",
                    "lastTeam": "Atlas",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/hector-raul-mancilla\/1044",
                    "rantingTD": "3",
                    "rantingTDL": "3",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1844",
                    "type": "PRESTAMO",
                    "nationality": "Mexicana",
                    "name": "Bravo, Omar",
                    "acquire": "Atlas",
                    "transfer": "Cruz Azul",
                    "lastTeam": "Cruz Azul",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/omar-bravo\/236",
                    "rantingTD": "3",
                    "rantingTDL": "3",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1708",
                    "type": "PRESTAMO",
                    "nationality": "Mexicana",
                    "name": "Santana, Sergio Alejandro",
                    "acquire": "Morelia",
                    "transfer": "Atlas",
                    "lastTeam": "Atlas",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/sergio-alejandro-santana\/179",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1801",
                    "type": "PRESTAMO",
                    "nationality": "Mexicana",
                    "name": "Santos, Flavio Jes\u00fas",
                    "acquire": "Toluca",
                    "transfer": "Atlas",
                    "lastTeam": "Atlas",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/flavio-jesus-santos\/2242",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1800",
                    "type": "PRESTAMO",
                    "nationality": "Mexicana",
                    "name": "Brizuela, Isaac",
                    "acquire": "Atlas",
                    "transfer": "Toluca",
                    "lastTeam": "Toluca",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/isaac-brizuela\/4450",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1777",
                    "type": "PRESTAMO",
                    "nationality": "Mexicana",
                    "name": "Razo, \u00d3scar Francisco",
                    "acquire": "Atlas",
                    "transfer": "Morelia",
                    "lastTeam": "Morelia",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/oscar-francisco-razo\/2016",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1817",
                    "type": "ALTA",
                    "nationality": "Mexicana",
                    "name": "Paganoni, Jes\u00fas Arturo",
                    "acquire": "Atlas",
                    "transfer": "Toluca",
                    "lastTeam": "Toluca",
                    "Detail": "Regresa tras pr\u00e9stamo",
                    "playerURL": "\/futbol\/jugadores\/jesus-arturo-paganoni\/2134",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1690",
                    "type": "ALTA",
                    "nationality": "Mexicana",
                    "name": "Rivera, Edson Ulises",
                    "acquire": "Atlas",
                    "transfer": "Braga",
                    "lastTeam": "Braga",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/edsonulisesrivera\/12668",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1667",
                    "type": "BAJA",
                    "nationality": "Ecuatoriana",
                    "name": "Bola\u00f1os, Luis Alberto",
                    "acquire": "Por definir",
                    "transfer": "Atlas",
                    "lastTeam": "Atlas",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/luis-bolanos\/3666",
                    "rantingTD": "2",
                    "rantingTDL": "2",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                }
            ]
        },
        {
            "id": "4",
            "name": "Cruz Azul",
            "teamAdd": "3",
            "teamDelete": "4",
            "teamRumor": "0",
            "groupName": "",
            "groupId": "",
            "SquadURL": "",
            "logos": [
                {
                    "size": "70x70",
                    "type": "gif",
                    "URL": "http:\/\/i2.esmas.com\/deportes30\/img\/mxmlogos\/cruz_azul.gif"
                },
                {
                    "size": "129x130",
                    "type": "jpg",
                    "URL": "http:\/\/i2.esmas.com\/deportes30\/img\/draft\/emb_cruzazul_draft.jpg"
                }
            ],
            "operation": [
                {
                    "id": "1887",
                    "type": "ALTA",
                    "nationality": "Argentina",
                    "name": "Bertolo, Nicol\u00e1s Santiago",
                    "acquire": "Cruz Azul",
                    "transfer": "Palermo",
                    "lastTeam": "Palermo",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/nicolassantiagobertolo\/17531",
                    "rantingTD": "3",
                    "rantingTDL": "3",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1841",
                    "type": "ALTA",
                    "nationality": "Colombiana",
                    "name": "Guti\u00e9rrez, Te\u00f3filo Antonio",
                    "acquire": "Cruz Azul",
                    "transfer": "Junior",
                    "lastTeam": "Junior",
                    "Detail": "",
                    "playerURL": "\/futbol\/jugadores\/teofiloantoniogutierrez\/4721",
                    "rantingTD": "4",
                    "rantingTDL": "4",
                    "ratingUser": "0",
                    "ratingUserL": "0"
                },
                {
                    "id": "1834",
                    "type": "PRESTAMO",
                }
            ]
        }
    ]
})        